server:
  port: 9090

spring:
  application:
    name: backend-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO