version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data  # ✅ Đường dẫn đúng của PostgreSQL
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5431:5432'  # Máy host: 5431 -> Container: 5432
    networks:
      - default

  backend-service:
    container_name: backend-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres  # ✅ Đảm bảo Postgres khởi động trước
    ports:
      - "9090:9090"
    environment:
      DATABASE_HOST: postgres  # ✅ Kết nối với PostgreSQL trong Docker Network
      DATABASE_PORT: 5432  # ✅ Dùng cổng 5432 của container
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: 12345
      LOGSTASH_HOST: logstash:5600
    networks:
      - default

  elastic-search:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - default

  kibana:
    image: kibana:7.14.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    networks:
      - default

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - '7080:8080'
      - '50000:50000'
    container_name: jenkins
    networks:
      - default
    volumes:
      - ~/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  logstash:
    image: logstash:7.14.1
    container_name: logstash
    restart: always
    ports:
      - "5600:5600"
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      - default

networks:
  default:
    name: backend-service

volumes:
  postgres_data:
